using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// ï¿½ï¿½Ã¼ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿?Å¬ï¿½ï¿½ï¿½ï¿½
/// </summary>
/// 

public enum MonsterState
{
    Idle = 0, 
    Moving = 1, 
    Attack = 2,
    GetHit = 3,
    CritcalAttack = 4 
}

public enum MonsterType
{
    Normal,
    Boss
}

public class Monster : MonoBehaviour
{
    public MonsterData monsterData; // ï¿½ï¿½ï¿½Í¸ï¿½ï¿½ï¿½ ï¿½Ø´ï¿½ï¿½Ï´ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½Ö±ï¿½

    public MonsterState state;
    public MonsterType monsterType;

    private Animator anim;
    private SpriteRenderer warning;

    protected bool isLive;
    public float addDamage = 3;

    void Awake()
    {
        anim = GetComponent<Animator>();
        warning = GetComponentInChildren<SpriteRenderer>();

        isLive = true; // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ® È°ï¿½ï¿½È­ ï¿½ï¿½ 
        monsterData.Hp = monsterData.MaxHp; // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ® È°ï¿½ï¿½È­ ï¿½ï¿½ 

    }

    void Start()
    {
        Init();
    }


    // [0] ï¿½ï¿½ï¿½ï¿½ ï¿½Ê±ï¿½È­
    public void Init()
    {
        state = MonsterState.Idle;
        anim.SetInteger("State", (int)state);
    }

    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Space))
        {
            /*GetHit();*/
            Die();
        }

    }

    // [1] ï¿½Ï¹ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
    public void ReadyToAttack()
    {
        Player player = FindObjectOfType<Player>();

        float playerHp = player.playerData.Hp;
        float randDamage = Random.Range(monsterData.MinDamage, monsterData.MaxDamage);
        float critcalDamage = monsterData.MinDamage + addDamage;

        playerHp -= randDamage;

        if (randDamage >= critcalDamage)
        {
            state = MonsterState.CritcalAttack;
            anim.SetInteger("State", (int)state);
            Debug.Log("ÇÃ·¹ÀÌ¾î:" + playerHp + $", ï¿½ï¿½ï¿½ï¿½{(int)randDamage} Ä¡ï¿½ï¿½Å¸ ï¿½ï¿½ï¿½ï¿½!");
            return;
        }
        else
        {
            state = MonsterState.Attack;
            anim.SetInteger("State", (int)state);
            Debug.Log("ï¿½Ã·ï¿½ï¿½Ì¾ï¿½ Ã¼ï¿½ï¿½:" + (int)playerHp + $", ï¿½ï¿½ï¿½ï¿½{(int)randDamage} ï¿½ï¿½ï¿½ï¿½!");
            return;
        }
    }


    // [2] ï¿½ï¿½ï¿½ï¿½ ï¿½Ç°ï¿½ Ã³ï¿½ï¿½
    public void GetHit()
    {
        if (!isLive)
            return;

        float playerDamage = FindObjectOfType<Player>().playerData.Damage;
        monsterData.Hp -= playerDamage;

        Debug.Log("ï¿½ï¿½ï¿½ï¿½ Ã¼ï¿½ï¿½" + (int)monsterData.Hp);

        if (monsterData.Hp <= 0)
        {
            Die();
        }

        state = MonsterState.GetHit;
        anim.SetInteger("State", (int)state);

    }

    // [2-1] ï¿½ï¿½ï¿½ï¿½ ï¿½Ç°ï¿½ ï¿½ï¿½ ï¿½Ìºï¿½Æ® Ã³ï¿½ï¿½
    public void EventToGetHit()
    {
        // GetHit ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿?
        // ï¿½ï¿½ï¿½ï¿½ ï¿½Ç°ï¿½ ï¿½ï¿½ Color ï¿½ï¿½ï¿½ï¿½ 
    }


    // [3] ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿?Ã³ï¿½ï¿½
    public void Die()
    {
        /*if (isLive) 
            return;*/

        // ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿?ï¿½ï¿½ isWall ï¿½ï¿½ï¿½ï¿½
        MapGenerator.instatnce.totalMap[(int)transform.position.x, (int)transform.position.z]
            .SetCoord((int)transform.position.x, (int)transform.position.z, false);

        anim.SetTrigger("Die");
    }

    // [3-1] ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿?ï¿½ï¿½ ï¿½Ìºï¿½Æ® Ã³ï¿½ï¿½
    public void EventToDie()
    {
        // ï¿½ï¿½Æ¼Å¬ ï¿½ï¿½ï¿½ï¿½
        // ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿?ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿?    
    }
}
